```yaml
version: 2

sources:
  - name: raw
    database: hive_metastore
    schema: raw
    tables:
      - name: raw_business_accounts
        description: "Source table containing raw business account data."
      - name: raw_transactions
        description: "Source table containing raw transactions data."
```